site_name: Docker Compose Package Manager
repo_name: 'hweeks/dcpm'
repo_url: 'https://github.com/hweeks/dcpm/tree/master/packages/docs'
theme:
  logo:
    icon: 'tab'
  palette:
    primary: 'orange'
    accent: 'deep orange'
  name: 'material'
  font:
    text: 'Montserrat'
    code: 'Cousine'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
